brew "zsh"
brew "tmux"
brew "vim"
brew "neovim"
brew "fzf"
brew "fd"
brew "ripgrep"
brew "the_silver_searcher"

brew "mise"
brew "jemalloc"
brew "cmake"
brew "htop"
brew "nginx"
brew "imagemagick"
brew "vips"
brew "wget"

brew "rclone"

brew "gallery-dl"
brew "wireguard-tools"

# Better encryption for encrypted zip archives
# brew "p7zip"

cask "betterdisplay"
cask "ghostty"
cask "libreoffice"
cask "microsoft-teams"
cask "google-chrome"
cask "sublime-text"
cask "affinity-photo"
cask "affinity-designer"
