call plug#begin('~/.vim/plugged')

" let g:ale_disable_lsp = 1

" Global search by ack cli util
Plug('mileszs/ack.vim')
" Plug('wincent/ferret')

" Filetree
Plug('scrooloose/nerdtree')

" Plug('github/copilot.vim')

" TODO: Replace nerdtree with fern
" Plug('lambdalisue/fern.vim')

" Comments
Plug('tpope/vim-commentary')

" Perform all your vim insert mode completions with Tab
" Plug('ervandew/supertab')

" Most old autocomplete
" Plug('lifepillar/vim-mucomplete')

" Autocomplete & intellisense
" Coc is an intellisense engine for Vim/Neovim.
" Also adds linting and snipets
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Enable in 2023
" if has('nvim')
"   Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
" endif

" Popup for VIM built-in autocomplete https://github.com/vim-scripts/AutoComplPop
"Plug("vim-scripts/AutoComplPop")

" Linting
Plug('w0rp/ale')

Plug 'catppuccin/vim', { 'as': 'catppuccin' }

" Statusline
Plug('itchyny/lightline.vim')

" Base16 colors for lightline
Plug('daviesjamie/vim-base16-lightline')
"
" Show ale errors in lightline
" Plug('maximbaz/lightline-ale')

" Alternative linting plugin(Consider to switch in future)
" Plug('neomake/neomake')

" Enable repeating supported plugin maps with '.'
Plug('tpope/vim-repeat')

" FZF integration
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Show changed lines from git
Plug('airblade/vim-gitgutter')
" mhinz/vim-signify

" Lightweight support for Ruby's Bundler
Plug('tpope/vim-bundler')

" Ruby on Rails power tool
" This is a massive (in a good way) Vim plugin for editing Ruby on Rails applications.
" Partial and concern extraction. In a view, :Extract {file} replaces the
" desired range (typically selected in visual line mode) with render '{file}',
" which is automatically created with your content. In a model or controller, a
" concern is created, with the appropriate include declaration left behind.
" :help rails-:Extract
Plug('tpope/vim-rails')

" Minimal rbenv support
Plug('tpope/vim-rbenv')

" Better rspec syntax highlighting for Vim
Plug('keith/rspec.vim')

" Ruby syntax highlighting
Plug('vim-ruby/vim-ruby')

" Vim highlighting & completion for MiniTest
Plug('sunaku/vim-ruby-minitest')

" Create your own text objects
Plug('kana/vim-textobj-user')

" Make text objects with various ruby block structures.
Plug('rhysd/vim-textobj-ruby')

Plug('michaeljsmith/vim-indent-object')

" Automaticaly add end in ruby scrips
Plug('tpope/vim-endwise')

" quoting/parenthesizing made simple
Plug('tpope/vim-surround')

" Provides additional text objects
" Example:
" ci* - change inside star
" va| - visually select around pipe
" ci_ - change inside underscore
" ca/aa/Ia/Aa  - change inside function/method argument

Plug('wellle/targets.vim')

" Run various tests from vim
Plug('janko-m/vim-test')

" Easily navigate between vim and tmux panes
Plug('christoomey/vim-tmux-navigator')

" Allows vim to communicate and run commands in tmux
Plug('benmills/vimux')

" CSS3 syntax support
Plug('hail2u/vim-css3-syntax')

" Git integration
Plug('tpope/vim-fugitive')

" Make terminal vim and tmux work better together.
Plug('tmux-plugins/vim-tmux-focus-events')

" Provides insert mode auto-completion for quotes, parens, brackets
Plug('Raimondi/delimitMate')

" TypeScript syntax
" Plug('leafgarland/typescript-vim')

" Crystal syntax support
Plug('rhysd/vim-crystal')

" Reslove git conflicts
" Plug('christoomey/vim-conflicted')

" Improved JavaScript syntax
Plug('pangloss/vim-javascript')

" Alternative JavaScript syntax
" Plug 'maxmellon/vim-jsx-pretty'


" JSX syntax support
Plug('mxw/vim-jsx')

" Multiple cursors
" Plug('terryma/vim-multiple-cursors') " This plugin is deprecated

" Multiple cursors
Plug('mg979/vim-visual-multi')

" Brewfile syntax highlighting
Plug('bfontaine/brewfile.vim')

" Auto close (X)HTML tags
Plug('alvan/vim-closetag')

" Emmet
Plug('mattn/emmet-vim')

" Base16 color schemes
Plug('chriskempson/base16-vim')
"" shows yaml path under cursor,
" allows to search by YAML key
Plug('Einenlum/yaml-revealer')

" Snippets
" Plug('SirVer/ultisnips')
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug('garbas/vim-snipmate')

" Snippets usging coc.nvim
" https://github.com/neoclide/coc-snippets

" Automatically highlighting other uses of the current word under the cursor
" Plug('RRethy/vim-illuminate')

" Better yaml folding
Plug 'pedrohdz/vim-yaml-folds'

" Lighline base16 themes
Plug 'nolo18/base16lightline'

" Highligh color codes
Plug('lilydjwg/colorizer')

" Vue syntax
" Plug('posva/vim-vue')
" Plug('storyn26383/vim-vue')

" AppArmor syntax highlight
Plug('ClockworkNet/vim-apparmor')

" Improved nginx vim plugin (incl. syntax highlighting)
Plug('chr4/nginx.vim')

" JSON highlight
Plug('elzr/vim-json')

" Syntax highlighting and filetype detection for systemd unit files
Plug('wgwoods/vim-systemd-syntax')

" " Syntax highlighting for Nix configs
" Plug('LnL7/vim-nix')

" Dracula color scheme
Plug('dracula/vim')

" A vim colorscheme for use with wal
" Plug('dylanaraps/wal.vim')

" Colorscheme
" Plug('jacoborus/tender.vim')
Plug('nolo18/base16lightline')

" Better markdown support
Plug('plasticboy/vim-markdown')

" unimpaired.vim: Pairs of handy bracket mappings
Plug('tpope/vim-unimpaired')

" GTK Blueprint syntax
Plug('thetek42/vim-blueprint-syntax')

" Switch between multiline and signleline code
Plug('AndrewRadev/splitjoin.vim')

" Switch between different things
Plug('AndrewRadev/switch.vim')

" Better YAML folding
Plug('pedrohdz/vim-yaml-folds')

" YAML revealer: shows yaml path under cursor,
" allows to search by YAML key
Plug('Einenlum/yaml-revealer')

" Highlight matching HTML tag
Plug('leafOfTree/vim-matchtag')

" Measure startuptime
Plug('dstein64/vim-startuptime')

call plug#end()
"============================================================================
" ===================== General settings ====================================
"============================================================================

" VIM built-in autocomplete options
" Autocomple word spelling
" set spell "kpelllang=en_us
set complete+=kspell
set completeopt+=preview,menuone
" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" use the space key as our leader. put this near the top of your vimrc
" Disable default space mapping
nnoremap <space> <nop>
" Make space Leader
let mapleader = "\<space>"

" r For auto indent filetype plugin indent on
syntax on
filetype plugin on

" Use vim, not vi api
set nocompatible

" Redraw only when we need to (i.e. don't redraw when executing a macro)
set lazyredraw

" Indicates a fast terminal connection.  More characters will be sent to the
" screen for redrawing, instead of using insert/delete line commands.
" Improves smoothness of redrawing when there are multiple windows and the
" terminal does not support a scrolling region.
" Experimental
set ttyfast

" No backup files
set nobackup

" No write backup
set nowritebackup

" No swap file
set noswapfile

" Encrypted files encryption method
" set cm=blowfish2 " doesnt work in neovim

" Command history
set history=500

" Remove escape delay http://www.johnhawthorn.com/2012/09/vi-escape-delays/
" set timeoutlen=1000 ttimeoutlen=0
set timeoutlen=350
set ttimeoutlen=10

" Always show cursor
set ruler

" Highligh current line
set cursorline

" Show incomplete commands
set showcmd

" Incremental searching (search as you type)
set incsearch

" Highlight search matches
set hlsearch

" Ignore case in search if term(s) are lowercase
set ignorecase

" Search with case sensitivity if term(s) are upper or mixed case
set smartcase

" Turn word wrap off
set nowrap

" Wrap lines at convenient points
set linebreak

" Indent settings
set autoindent
set smartindent

" Performance
" syntax sync maxlines=256
syntax sync maxlines=1000
set synmaxcol=200

" Allow backspace to delete end of line, indent and start of line characters
set backspace=indent,eol,start

set background=dark

" Base16 hook
" if filereadable(expand("~/.vimrc_background"))
"    let base16colorspace=256
"    source ~/.vimrc_background
" endif

" colorscheme base16-horizon-dark

" Use pywal colorscheme
" colorscheme wal
colorscheme dracula
" colorscheme catppuccin_frappe

" colorscheme one

" colorscheme tender

let g:custom_color_character = '#98c379'

" Access colors present in 256 colorspace
let base16colorspace=256
set t_Co=256

" Use 24bit(True color) GUI colors
" VIM syntax highlight will work in gui mode(guifg, guibg)
set termguicolors

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Always show statusline
set laststatus=2

" Always display the tabline, even if there is only one tab
set showtabline=2

" Hide the default mode text (e.g. -- INSERT -- below the statusline)
set noshowmode

" Enable mouse
set mouse=a

" fix mouse support inside tmux
" Doesnt work in neovim
" set ttymouse=xterm2

" Set number of lines
set nu!

" Tabulation settinngs
set ts=2
set sts=0
set sw=2

" Tabs settins
" Convert tabs to spaces, all file types
set expandtab

" Set tab size in spaces (this is for manual indenting)
set tabstop=2

" The number of spaces inserted for a tab (used for auto indenting)
set shiftwidth=2

" Turn on line numbers
set number

" UTF encoding
set encoding=utf-8
" set spelllang=en

" Autoload files that have changed outside of vim
set autoread

" Better splits (new windows appear below and to the right)
set splitbelow
set splitright

" Ensure Vim doesn't beep at you every time you make a mistype
set visualbell

" Visual autocomplete for command menu (e.g. :e ~/path/to/file)
set wildmenu

" Automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" ========== Additional syntax definitions ========================
" Highlight crontab and anacrontab files
autocmd BufNewFile,BufRead crontab,anacrontab set syntax=crontab

" Highlight ActiveAdmin rails administation framework templates
autocmd BufRead,BufNewFile *.arb setfiletype ruby

" Highlight a matching [{()}?P] when cursor is placed on start/end character
set showmatch

" Complete files like a shell.
set wildmode=list:longest

" Show 3 lines of context around the cursor.
set scrolloff=3

" Set the terminal's title
set title

" Yank to vim clipboard
set clipboard+=unnamed

" Yank to system clipboard
" set clipboard+=nnamedplus

set nofoldenable
set foldlevelstart=3

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("nvim-0.5.0") || has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif

" Reference chart of values:
"   Ps = 0  -> blinking block.
"   Ps = 1  -> blinking block (default).
"   Ps = 2  -> steady block.
"   Ps = 3  -> blinking underline.
"   Ps = 4  -> steady underline.
"   Ps = 5  -> blinking bar (xterm).
"   Ps = 6  -> steady bar (xterm).
" Set cursor shapes (Insert: thin bar, Normal: block)
let &t_SI = "\<Esc>[6 q"
let &t_EI = "\<Esc>[2 q"
" For this to work import to have the following ESC delay timeout settings:
" Remove escape delay http://www.johnhawthorn.com/2012/09/vi-escape-delays/
" set timeoutlen=350
" set ttimeoutlen=10

"============================================================================
"====================== Highlight ============================================
"============================================================================

" Enable italic for comments
hi Comment gui=italic cterm=italic

"============================================================================
"====================== Autocommands ============================================
"============================================================================

" Auto remove trailing blank spaces on each save
autocmd BufWritePre * :%s/\s\+$//e

" Set textwidth 75 for markdown files
au BufRead,BufNewFile *.md setlocal textwidth=75

" Force Ruby syntax for Pry config file
autocmd BufRead,BufNewFile .pryrc setlocal syntax=ruby

if has("nvim")
  " Highligh text on yank
  au TextYankPost * silent! lua vim.highlight.on_yank {higroup="Type", timeout=250}
endif

"============================================================================
"================== YAML settings ===========================================
"============================================================================
" Set folding rules for yaml
au! BufNewFile,BufReadPost *.{yaml,yml} set filetype=yaml foldmethod=indent
" By default fold just opened yaml file
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab foldenable

" Set folding rules for html and erb files
au! BufNewFile,BufReadPost *.{html} set filetype=html foldmethod=indent
au! BufNewFile,BufReadPost *.{erb} set filetype=eruby foldmethod=indent
autocmd FileType html setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType eruby setlocal ts=2 sts=2 sw=2 expandtab

"============================================================================
"====================== Mapings =============================================
"============================================================================

" Double click on left mouse button trigers Insert mode
" map <2-LeftMouse> #

" map <RightMouse> n
" map <2-RightMouse> n

" Remap VIM 0 to first non-blank character
nnoremap 0 ^

" Pressing will toggle and untoggle spell checking
" map <Leader>custom :setlocal spell!<cr>

" Save current file
nnoremap <Leader>w :w<CR>

" Go to the begining of line
noremap H ^

" Go to the end of line
noremap L $

" Run 'git blame' on a selection of code
nmap <Leader>gb :Git blame<CR>

" Run 'git status' for current file
" nmap <Leader>gs :Gstatus<CR>

" Change surround double quotes to plain quotes
nmap <Leader>' cs"'<CR>
"
" Change surround single quotes to double quotes
nmap <Leader>" cs'"<CR>

" Shift + q - Quit
map Q <C-W>q

" Faster search
" nnoremap s /

" Fix indenting selection
vnoremap < <gv
vnoremap > >gv

" Open a new tab with Ctrl+T
nnoremap <C-t> <esc>:tabnew<CR>

" For indenting code
" map <Leader>i mmgg=G`m<CR>

" Disable selection
nnoremap <silent> <Leader>n :nohl<CR>

" Enter replace command
" Global search and replace in quickfix menu
" nnoremap <Leader>r :%s/
" nnoremap s :%s///gy<Left><Left><Left><Left>
nnoremap @ :%s///g<Left><Left><Left><Left>
nnoremap <leader>r :cfdo %s///g \| update <left><left><left><left><left><left><left><left><left><left><left><left><left>


" Edit vim config
nnoremap <Leader>ve :e ~/.vim/vimrc<cr>

" Reload vim config
nnoremap <Leader>vr :source $MYVIMRC<cr>

" Reload servers
" nnoremap q :call RestartServers() <CR>
" nnoremap q :call

" Reload chrome tab
" nnoremap R :call ReloadActiveChromeTab() <CR>

" Move up and down by visible lines if current line is wrapped
nmap j gj
nmap k gk
nmap K k

" Easily navigate between tabs
nnoremap E gT
nnoremap R gt

" Copy selected text to system clipboard
vnoremap m "+y

" Copy current line to system clipboard
nnoremap ` "+yy

" Copy full path of the current file to the clipboard
" nnoremap <silent> R :let @+ = expand('%:p')<CR>
"
" Copy relative path of the current file to the clipboard
nnoremap <silent> R :let @+ = expand('%')<CR>

" nnoremap ` :q<CR>

" Easily resize windows
nnoremap < <C-w>5<
nnoremap > <C-w>5>
nnoremap + <C-w>5+
nnoremap _ <C-w>5-

"=========== Move lines ===============
" Move multipe lines up in visual mode
" vnoremap <C-k> :m '<-2<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Move multipe lines down in visual mode
" vnoremap <C-j> :m '<-2<CR>gv=gv
vnoremap J :m '>+1<CR>gv=gv

" " Move multiple lines selected
" vmap <C-k> [egv
" vmap <C-j> ]egv

" zoom a vim pane, <C-w>= to re-balance
" nmap <C-w><cr> <C-W>\| <C-W>_

" Switch between tabs
nnoremap <C-q> :tabprev<cr>
nnoremap <C-e> :tabnext<cr>

" Toggle folding
" nnoremap <C-s> za
nnoremap K za

" Toggle folding with left mouse button click
map <2-LeftMouse> za

" Tabs
nnoremap <C-Left> :tabprev<cr>
nnoremap <C-Right> :tabnext<cr>
nnoremap <TAB> :tabnext<cr>

" nnoremap H gT
" nnoremap <A-k> :tabprev<CR>
" nnoremap <A-j> :tabnext<CR>
" noremap L gt

" Map text align to tab button in visual mode
vnoremap <TAB> =

" nnoremap <TAB> gt

" Expand window
nmap " <C-W>\| <C-W>_

" Toggle windows layout mode
" nnoremap K <C-w>H
" nnoremap F <C-w>J

" Re-balance panes
nnoremap = <C-W>=

" Toggle current window zoom
nnoremap m :ToggleCurrentWindowZoom <CR>

" Swith between tabs
" nnoremap m gt

" Select tab by number
" 'ctrl-m 1' - selects first tab, etc
for i in range(1, 9)
  execute "nnoremap \<C-w>" . i . " " . i . "gt<CR>"
endfor

" Select tab by number
" 'Leader 1' - selects first tab, etc
for i in range(1, 9)
  execute "nnoremap \<Leader>" . i . " " . i . "gt<CR>"
endfor

" Yank(copy), comment and paste (usefull for refactoring)
vnoremap M yV'] gcc']pjj
" nnoremap M yy']:TComment<CR>']pjj

" Faster close windows and quit
" nnoremap <C-c> <C-w>q
nnoremap <C-c> <C-w>q

" Test runner mappings
nnoremap <silent> <Leader>t :TestNearest<CR>
nnoremap <silent> <Leader>T :TestFile<CR>
nnoremap <silent> <Leader>a :TestSuite<CR>
nnoremap <silent> <Leader>l :TestLast<CR>

" Go to related file
nnoremap <Leader>e :R<CR>

" Go to alternate file
nnoremap q :GFiles?<CR>

" Auto indent pasted text
" nnoremap p p=`]<C-o>
" nnoremap P P=`]<C-o>

" Move to the end of yanked text after yank and paste
nnoremap p p`]
vnoremap y y`]
vnoremap p p`]

" Fixes pasting after visual selection.
xnoremap p "_dP

" Switch to last file
" nnoremap R <c-^>

" Tcomment
" Comment line in visual mode
vnoremap <Leader><Tab> gcc<CR>

" Comment line in normal mode
nnoremap <Leader><Tab> gcc<CR>


"=========================================================================
"====================== FZF settings =====================================
"=========================================================================
" fzf
set rtp+=~/.fzf

let g:fzf_layout = { 'window': { 'width': 1, 'height': 0.8 } }
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Conditional'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Conditional'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Statement'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

command! -bang -nargs=? -complete=dir Files
      \ call fzf#vim#files(<q-args>, { 'window': { 'height': 1, 'width': 1 }, 'options': ['--info=inline', '--preview', '~/.vim/plugged/fzf.vim/bin/preview.sh {}']}, <bang>0)

" Files fzf command shows preview
command! -nargs=1 FuzzySearchFileInDir FZF <args>

nnoremap <C-p> :FZF<CR>
" nnoremap <C-p> :Files<CR>

"To learn more about preview window options, see `--preview-window` section of `man fzf`.
let g:fzf_preview_window = ['up:52%', 'ctrl-/']

" Custom full text search by FZF and AG(no preview window)
noremap <Leader>p :CustomFullTextSearch <CR>

" fzf.vim Full text search in fullscreen by AG(with preview window)
" "!" indicates for FZF that FZf should be opened in fullscreen
noremap <Leader>o :Ag! <CR>

" Search sibling files in same directory as current file(with preview window)
noremap <Leader>i :FuzzySearchSiblingFilesInCurrentDir <CR>

" Search javascripts
noremap <Leader>j :FuzzySearchFileInDir app/assets/javascripts <CR>

" Search app/models by FZF
noremap <Leader>m :FuzzySearchFileInDir app/models<CR>

" Search app/assets/stylesheets by FZF
noremap <Leader>s :FuzzySearchFileInDir app/assets/stylesheets<CR>

" Search app/views by FZF
nnoremap <Leader>d :FuzzySearchFileInDir app/views<CR>

" Search app/components by FZF
nnoremap <Leader>f :FuzzySearchFileInDir app/components<CR>

" Search app/locales by FZF
nnoremap <Leader>b :FuzzySearchFileInDir config/locales<CR>

" Search app/controllers by FZF
noremap <Leader>c :FuzzySearchFileInDir app/controllers<CR>

function! s:fzf_neighbouring_files()
  let current_file =expand("%")
  " Shows full absolute path
  " let cwd = fnamemodify(current_file, ':p:h')
  " Shows filename and dirname path
  let cwd = fnamemodify(current_file, ':h')
  " let command = 'ag -g "" -f ' . cwd . ' --depth 0'
  let command = 'ag -g "" -f ' . cwd . ' --depth 0'

  call fzf#run({
        \ 'source': command,
        \ 'sink':   'e',
        \ 'options': ['-m', '-x', '+s', '--info=inline', '--preview', '~/.vim/plugged/fzf.vim/bin/preview.sh {}'],
        \ 'window':  { 'height': 0.8 , 'width': 1 } })
endfunction

command! FuzzySearchSiblingFilesInCurrentDir call s:fzf_neighbouring_files()

" Full text search support for FZF
function! s:ag_to_qf(line)
  let parts = split(a:line, ':')
  return {'filename': parts[0], 'lnum': parts[1], 'col': parts[2],
        \ 'text': join(parts[3:], ':')}
endfunction

function! s:ag_handler(lines)
  if len(a:lines) < 2 | return | endif

  let cmd = get({'ctrl-x': 'split',
               \ 'ctrl-v': 'vertical split',
               \ 'ctrl-t': 'tabe'}, a:lines[0], 'e')
  let list = map(a:lines[1:], 's:ag_to_qf(v:val)')

  let first = list[0]
  execute cmd escape(first.filename, ' %#\')
  execute first.lnum
  execute 'normal!' first.col.'|zz'

  if len(list) > 1
    call setqflist(list)
    copen
    wincmd p
  endif
endfunction

" CustomFullTextSearch command does full text search by FZF
command! -nargs=* CustomFullTextSearch call fzf#run({
      \ 'source':  printf('ag --nogroup --column --color "%s"',
      \                   escape(empty(<q-args>) ? '^(?=.)' : <q-args>, '"\')),
      \ 'sink*':    function('<sid>ag_handler'),
      \ 'options': '--ansi --expect=ctrl-t,ctrl-v,ctrl-x --delimiter : --nth 4.. '.
      \            '--multi --bind=ctrl-a:select-all,ctrl-d:deselect-all '.
      \            '--color hl:68,hl+:110',
      \ 'down':    '50%'
      \ })


command! ProjectFiles execute 'Files!' s:find_git_root()

function! s:find_git_root()
  return system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
endfunction


"=========================================================================
"====================== Ack settings =====================================
"=========================================================================
" Ack mappings
nnoremap ! :Ack<SPACE>

" Ack: To go to the next search result
nnoremap <leader>] :cn<CR>

" Ack: To go to the previous search results
nnoremap <leader>[ :cp<CR>

" TODO add mapping for spliting tmux and running rails console
" Maps gX to use xdg-open with the filepath under cursor
nnoremap gx :silent :execute "!xdg-open" expand('%:p:h') . "/" . expand("<cfile>") " &"<cr>

"============================================================================
"================== Ctags additional mappings ===============================
"============================================================================
" To to prev tag
nnoremap <Leader>= :tprev<CR>

" To to next tag
nnoremap <Leader>- :tnext<CR>

"============================================================================
"================== Snippets mappings =======================================
"============================================================================

" Snipmate go to previos stop point in snippet
imap <C-o> <C-R>=snipMate#BackwardsSnippet()<CR>
vnoremap <C-o> :call snipMate#BackwardsSnippet()<CR>
smap <C-o> <Esc>a<C-R>=snipMate#BackwardsSnippet()<CR>

" Snipmate expand snippet
imap <silent><C-k> <C-R>=snipMate#TriggerSnippet()<CR>
smap <C-k> :call snipMate#TriggerSnippet() <CR>
smap <silent><C-k> <Esc>a<C-R>=snipMate#TriggerSnippet()<CR>


"============================================================================
"================= Splitjoin settings  ======================================
"============================================================================
" Split one line of code into multiple
nmap <Leader>8 gS
vmap <Leader>8 gS
"
" " Split multiple lines of code into one
nmap <Leader>7 gJ
vmap <Leader>7 gJ

" Search yaml line by key provided by Einenlum/yaml-revealer
" map <Leader>b :call SearchYamlKey()<CR>
" nnoremap <Leader>u :call SearchYamlKey()<CR>
" nnoremap R :call SearchYamlKey()<CR>

"============================================================================
"================= Snipmate settings  =======================================
"============================================================================
let g:snipMate = { 'snippet_version' : 1 }
let g:snipMate.no_default_aliases = 1
let g:snipMate.scope_aliases = {}
let g:snipMate.scope_aliases.ruby = 'ruby,rails'
let g:snipMate.scope_aliases['scss'] = 'css'

"============================================================================
"=================== RRethy/vim-illuminate settings =========================
"============================================================================
" Enable only for certain filetypes
let g:Illuminate_ftwhitelist = ['vim', 'sh', 'python', 'ruby', 'eruby', 'javascript']

" Set deplay before highlight
let g:Illuminate_delay = 500

" Change highlight style
augroup illuminate_augroup
    autocmd!
    autocmd VimEnter * hi illuminatedWord guibg=#34394d
    autocmd VimEnter * hi illuminatedCurWord cterm=NONE gui=NONE
augroup END

"
"============================================================================
"=================== vim-test settings ======================================
"============================================================================
"Open ruby test in tmux pane
let test#strategy = "vimux"
"
" Use bundle exec for ruby tests
let test#ruby#bundle_exec = 1

" Run rspec with spring preloader
" Temporary disable for current project without spring
" let test#ruby#rspec#executable = 'rsx'

"============================================================================
"=================== vimux settings =========================================
"============================================================================
" Use vertical tmux slpit for vimux commands
let g:VimuxOrientation = "h"

" Open vimux tmux pane with 50% width of screen
let g:VimuxHeight = "50"

" Ack (the_silver_searcher / ag)
let g:ackprg="ag"

let g:closetag_filenames = '*.html,*.xhtml,*.jsx, *.js'

"============================================================================
"===================== Fugitive settings ====================================
"============================================================================
" Froce to split window verticaly when fugitive opens git diff
set diffopt+=vertical

"============================================================================
" ===================== Nerdtree settings  ====================================
"============================================================================
" Show hidden files
let NERDTreeShowHidden=1

let NERDTreeWinSize=40

" Disable default Ctrl-\ mapping
nnoremap <C-\> <NOP>

" Toggle NERDTree
nnoremap <C-\> :NERDTreeToggle<CR>
nnoremap <Leader>0 :NERDTreeFind<CR>

autocmd VimEnter * nnoremap <C-\> :NERDTreeToggle<CR>
autocmd VimEnter * nnoremap <Leader>0 :NERDTreeFind<CR>

" Disable json plugin conceal
let g:vim_json_syntax_conceal = 0

" ===================== vim-markdown settings  ====================================
" Disabled folding of headers by default
let g:vim_markdown_folding_disabled = 1

" ===================== Emmet settings  ====================================
" Expand html tag by Emmet
" imap <C-j> <C-y>,
imap <C-l> <C-y>,

" imap <expr>k<tab> emmet#expandAbbrIntelligent("\<tab>")
let g:user_emmet_settings = {
  \  'javascript.jsx' : {
    \      'extends' : 'jsx',
    \  },
  \}

" ===================== ALE settings  ====================================
let g:ale_sign_error = '✗✗'
let g:ale_sign_warning = '∆∆'
let g:ale_lint_delay = 1000
let g:ale_lint_on_text_changed = 'never'
let g:ale_set_balloons = 1
let g:ale_hover_to_preview = 1
" let g:ale_hover_to_floating_preview = 1

let g:ale_linters = {
\   'ruby': ['rubocop', 'reek'],
\}

let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'ruby': ['rubocop'],
\   'javascript': ['prettier', 'eslint'],
\   'typescript': ['eslint'],
\   'css': ['prettier']
\}

" ===================== vim-jsx ====================================
" default 0
let g:vim_jsx_pretty_colorful_config = 1

" vim-jsx
" By default, JSX syntax highlighting and indenting will be enabled only for
" files with the .jsx extension. If you would like JSX in .js files, add
let g:jsx_ext_required = 0

" ===================== Lightline settings  ====================================

" \'colorscheme': 'tender',
let g:lightline = {
      \ 'colorscheme': 'base16',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             ['dirname','filename', 'modified', 'filetype'] ],
      \   'right': [ [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_infos', 'linter_ok' ], ['zoom_status'], ['total_lines']],
      \ },
      \ 'inactive': {
      \   'left': [['filename'] ],
      \   'right': [['total_lines']],
      \ },
      \ 'component': {
      \   'total_lines': ' %l/%L '
      \ },
      \ 'component_function': {
      \   'zoom_status': 'IsCurrentWindowZoomed'
      \ },
      \ 'tab': {
      \   'active': [ 'tabnum', 'cwd', 'modified' ],
      \   'inactive': [ 'tabnum', 'cwd','modified' ]
      \  },
      \ 'tab_component_function': {
      \   'cwd': 'LighlineTabFilenameWithParentDir'
      \  }
      \}

function! LighlineTabFilenameWithParentDir(n) abort
  let buflist = tabpagebuflist(a:n)
  let winnr = tabpagewinnr(a:n)
  let bufnum = buflist[winnr - 1]
  let bufname = expand('#'.bufnum.':t')
  let buffullname = expand('#'.bufnum.':a')
  " let buffullname = expand('#')
  " return buffullname
  " return substitute(buffullname, '.*/\([^/]\+/\)', '\1', '')
  if strlen(bufname)
    return substitute(buffullname, '.*/\([^/]\+/\)', '\1', '')
  else
    return strlen(bufname) ? bufname : '[No Name]'
  endif
endfunction

function! IsCurrentWindowZoomed()
  if !exists("t:currentWindowZoomed")
    let t:currentWindowZoomed = 0
  end

  if t:currentWindowZoomed
    return '  ///   VIM WINDOW ZOOM    ///'
  else
    return ''
  endif
endfunction

" ========= Lighline Ale integration =====================
let g:lightline.component_expand = {
      \  'linter_checking': 'lightline#ale#checking',
      \  'linter_infos': 'lightline#ale#infos',
      \  'linter_warnings': 'lightline#ale#warnings',
      \  'linter_errors': 'lightline#ale#errors',
      \  'linter_ok': 'lightline#ale#ok',
      \ }

let g:lightline.component_type = {
      \     'linter_checking': 'right',
      \     'linter_infos': 'right',
      \     'linter_warnings': 'warning',
      \     'linter_errors': 'error',
      \     'linter_ok': 'right',
      \ }

" "================================= vim-rails settings ========================
" " example projections: https://gist.github.com/henrik/5676109
let g:rails_projections = {
 \   'app/components/*.rb': {
 \     'alternate': 'app/components/{}.haml',
 \     'related': 'app/components/{}.js'
 \   },
 \   'app/components/*.haml': {
 \     'alternate': 'app/components/{}.scss',
 \     'related': 'app/components/{}.js'
 \   },
 \   'app/components/*.js': {
 \     'alternate': 'app/components/{}.rb',
 \     'related': 'app/components/{}.scss'
 \   },
 \   'app/components/*.scss': {
 \     'alternate': 'app/components/{}.rb'
 \   },
\   'app/*.rb': {
\     'alternate': 'spec/{}_spec.rb'
\   },
\   'app/admin/*.rb': {
\     'alternate': 'spec/controllers/admin/{}_controller_spec.rb'
\   },
\   'spec/controllers/admin/*_controller_spec.rb': {
\     'alternate': 'app/admin/{}.rb'
\   }
\ }

let g:rails_gem_projections = {
  \ "activeadmin": {
  \   "app/admin/*.rb": {
  \     "command": "admin",
  \     "affinity": "model",
  \     "alternate": "app/models/{}.rb",
  \     "template": "ActiveAdmin.register {} do\nend",
  \    }
  \}
  \}

" ====================== Vim highlight tag settings ==========
highlight link matchTagError Todo

let g:vim_matchtag_highlight_cursor_on = 1

" ===================== coc.vim settings  ====================================
" " Set internal encoding of vim, not needed on neovim, since coc.nvim using some
" unicode characters in the file autoload/float.vim
set encoding=utf-8

" TextEdit might fail if hidden is not set.
" Buffers persist in the background without being opened in window
set hidden

" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup

" Give more space for displaying messages.
" set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

let g:coc_global_extensions = ['coc-tsserver', 'coc-solargraph', 'coc-css']

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.

inoremap <silent><expr> <Tab>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"


function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <Leader>k :call ShowDocumentation()<CR>

function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

" Symbol renaming.
nmap <leader>t <Plug>(coc-rename)

" Highlight the symbol and its references when holding the cursor.
" autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <Leader>)  <Plug>(coc-format-selected)
nmap <Leader>)  <Plug>(coc-format-selected)

" Coc vim support for scss
autocmd FileType scss setl iskeyword+=@-@
" ========================= End coc.vim config =============================

"============================================================================
"====================== Commands ===========================================
"============================================================================
" Toggles current window zoom
command! ToggleCurrentWindowZoom :call ToggleCurrentWindowZoom()

" Fix save file typos
command! W w
command! WQ wq
command! Wq wq
command! Q q

"============================================================================
"====================== Functions ===========================================
"============================================================================
" DEPRECATED
" function! RestartServers()
"   execute system("tmux send-keys -t 2.left C-c \" bundle exec rails s\" C-m")
"   execute system("tmux send-keys -t 3.left C-c \" bundle exec rails s -p 3001\" C-m")
"   execute system("tmux send-keys -t 5.left C-c \" bundle exec sidekiq\" C-m")
"   echo "Servers reloaded"
" endfunction

function! ReloadActiveChromeTab()
  let l:currentTerminalEmulator = system("xdotool getactivewindow")

  execute system('
     \ xdotool search --onlyvisible --class Chrome windowfocus key F5
     \ && xdotool windowfocus ' . l:currentTerminalEmulator)

  echo "Chrome tab reloaded"
endfunction

" Toggle zoom of current window
function! ToggleCurrentWindowZoom()
  if !exists("t:currentWindowZoomed")
    let t:currentWindowZoomed = 0
    " TODO check nerdtree state
  endif

  if t:currentWindowZoomed
    execute "normal \<C-W>="
    let t:currentWindowZoomed = 0
  else
    :NERDTreeClose
    execute "normal \<C-W>\| \<C-W>_"
    let t:currentWindowZoomed = 1
  endif
endfunction

" Custom highlight function
" Requires vim 'set termguicolors'
function! Highlight(group, color)
  exec "hi " a:group . " guifg=" . a:color
endfunction

" Custom highlight function with italic text
" Requires vim 'set termguicolors'
function! ItalicHighlight(group, color)
  exec "hi " a:group . " guifg=" . a:color . " gui=italic"
endfunction

" ===================== Custom highlighting  ====================================
hi! link TabLineSel Function
hi NonText guifg=#bebebe ctermfg=238 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE
hi SpecialKey guifg=#bebebe ctermfg=238 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE
let g:vim_jsx_pretty_colorful_config = 1 " default 0

" ========================= Helper for vim snippets =======================
fun! Current_Filename(...)
  let template = get(a:000, 0, "$1")
  let arg2 = get(a:000, 1, "")

  let basename = expand('%:t:r')

  if basename == ''
    return arg2
  else
    return substitute(template, '$1', basename, 'g')
  endif
endf
