call plug#begin('~/.vim/plugged')

" Global search by ack cli util
Plug('mileszs/ack.vim')

" Filetree
Plug('scrooloose/nerdtree')

" Comments
Plug('tomtom/tcomment_vim')

" Autocomplete
Plug('lifepillar/vim-mucomplete')

" Statusline
Plug('itchyny/lightline.vim')

" Linting
Plug('w0rp/ale')

" Enable repeating supported plugin maps with '.'
Plug('tpope/vim-repeat')

" Show changed lines from git
Plug('airblade/vim-gitgutter')

" Lightweight support for Ruby's Bundler
Plug('tpope/vim-bundler')

" Ruby on Rails power tool
" This is a massive (in a good way) Vim plugin for editing Ruby on Rails applications.
Plug('tpope/vim-rails')

" Minimal rbenv support
Plug('tpope/vim-rbenv')

" Better rspec syntax highlighting for Vim
Plug('keith/rspec.vim')

" Vim highlighting & completion for MiniTest
Plug('sunaku/vim-ruby-minitest')

" Make text objects with various ruby block structures.
Plug('rhysd/vim-textobj-ruby')

" Automaticaly add end in ruby scrips
Plug('tpope/vim-endwise')

" quoting/parenthesizing made simple
Plug('tpope/vim-surround')

" Run various tests from vim
Plug('janko-m/vim-test')

" Easily navigate between vim and tmux panes
Plug('christoomey/vim-tmux-navigator')

" Allows vim to communicate and run commands in tmux
Plug('benmills/vimux')

" CSS3 syntax support
Plug('hail2u/vim-css3-syntax')

" Git integration
Plug('tpope/vim-fugitive')

" Make terminal vim and tmux work better together.
Plug('tmux-plugins/vim-tmux-focus-events')

" Create your own text objects
Plug('kana/vim-textobj-user')

" Provides insert mode auto-completion for quotes, parens, brackets
Plug('Raimondi/delimitMate')

" TypeScript syntax
Plug('leafgarland/typescript-vim')

" Crystal syntax support
Plug('rhysd/vim-crystal')

" Reslove git conflicts
Plug('christoomey/vim-conflicted')

" Improved JavaScript syntax
Plug('pangloss/vim-javascript')

" JSX syntax support
Plug('mxw/vim-jsx')

" Multiple cursors
Plug('terryma/vim-multiple-cursors')

" Brewfile syntax highlighting
Plug('bfontaine/brewfile.vim')

" Auto close (X)HTML tags
Plug('alvan/vim-closetag')

" Emmet
" Plug('mattn/emmet-vim')

" Base16 color schemes
Plug('chriskempson/base16-vim')

" Onedark colorscheme
Plug('rakr/vim-one')

" Highligh color codes
Plug('lilydjwg/colorizer')

" Search and replace
Plug('brooth/far.vim')

" FZF
Plug('junegunn/fzf.vim')

" Local eslint
Plug('benjie/local-npm-bin.vim')

call plug#end()
"============================================================================
" ===================== General settings ====================================
"============================================================================

" use the space key as our leader. put this near the top of your vimrc
" Disable default space mapping
nnoremap <space> <nop>
" Make space Leader
let mapleader = "\<space>"

" r For auto indent filetype plugin indent on
syntax on

" Use vim, not vi api
set nocompatible

" No backup files
set nobackup

" No write backup
set nowritebackup

" No swap file
set noswapfile

" Command history
set history=500

" Remove escape delay http://www.johnhawthorn.com/2012/09/vi-escape-delays/
set timeoutlen=1000 ttimeoutlen=0

" Always show cursor
set ruler

" Highligh current line
set cursorline

" Show incomplete commands
set showcmd

" Incremental searching (search as you type)
set incsearch

" Highlight search matches
set hlsearch

" Ignore case in search if term(s) are lowercase
set ignorecase
" Search with case sensitivity if term(s) are upper or mixed case
set smartcase

" Turn word wrap off
set nowrap

set autoindent

set smartindent

" Performance
syntax sync maxlines=256
set synmaxcol=120

" Auto remove trailing blank spaces on each save
autocmd BufWritePre * :%s/\s\+$//e

" Allow backspace to delete end of line, indent and start of line characters
set backspace=indent,eol,start

set background=dark

" Base16 hook
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif

" colorscheme one

" if g:colors_name ==# "one" || g:colors_name ==# "base16-onedark"
" "   " let g:custom_color_regular = '#e06c75'
" "   " let g:custom_color_secondary_regular = '#be5046'
" "   " let g:custom_color_statement = '#c678dd'
" "   " let g:custom_color_noise = 'gray'
" "   " let g:custom_color_type = '#e5c07b'
" "   " let g:custom_color_special = '#61afef'
"   " let g:custom_color_character = '#98c379'
" elseif g:colors_name == "base16-gruvbox-dark-medium" || g:colors_name == "base16-gruvbox-dark-pale" || g:colors_name == "base16-gruvbox-dark-soft"
"   " let g:custom_color_character = '#98c379'
" endif
let g:custom_color_character = '#98c379'

" Access colors present in 256 colorspace
let base16colorspace=256
set t_Co=256

" Use 24bit(True color) GUI colors
" VIM syntax highlight will work in gui mode(guifg, guibg)
set termguicolors

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Enable italic for comments
hi Comment gui=italic cterm=italic

" Always show statusline
set laststatus=2

" Always display the tabline, even if there is only one tab
set showtabline=2

" Hide the default mode text (e.g. -- INSERT -- below the statusline)
set noshowmode

" Enable mouse
set mouse=a

" fix mouse support inside tmux
set ttymouse=xterm2

" Set number of lines
set nu!

" Tabulation settinngs
set ts=2
set sts=0
set sw=2

" Tabs settins
" Convert tabs to spaces, all file types
set expandtab

" Set tab size in spaces (this is for manual indenting)
set tabstop=2

" The number of spaces inserted for a tab (used for auto indenting)
set shiftwidth=2

" Turn on line numbers
set number

" UTF encoding
set encoding=utf-8
set spelllang=en

" Autoload files that have changed outside of vim
set autoread

" Better splits (new windows appear below and to the right)
set splitbelow
set splitright

" Ensure Vim doesn't beep at you every time you make a mistype
set visualbell

" Visual autocomplete for command menu (e.g. :e ~/path/to/file)
set wildmenu

" Automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" Highlight crontab and anacrontab files
autocmd BufNewFile,BufRead crontab,anacrontab set syntax=crontab

" Redraw only when we need to (i.e. don't redraw when executing a macro)
set lazyredraw

" Highlight a matching [{()}?P] when cursor is placed on start/end character
set showmatch

" Complete files like a shell.
set wildmode=list:longest


" Show 3 lines of context around the cursor.
set scrolloff=3

" Set the terminal's title
set title

" Yank to system clipboard
set clipboard+=unnamed

"============================================================================
"====================== Abbreviations ============================================
"============================================================================
" Frozen string literal for Ruby
ab fsl # frozen_string_literal: true

"============================================================================
"====================== Mapings ============================================
"============================================================================

" Remap VIM 0 to first non-blank character
nnoremap 0 ^

" Pressing ,ss will toggle and untoggle spell checking
map <Leader>ss :setlocal spell!<cr>

" Save current file
nnoremap <Leader>w :w<CR>
nnoremap <C-s> :w<CR>

" Go to the begining of line
noremap H ^

" Go to the end of line
noremap L $

" Run 'git blame' on a selection of code
nmap <Leader>gb :Gblame<CR>

" Run 'git status' for current file
nmap <Leader>gs :Gstatus<CR>

" Change surround double quotes to plain quotes
nmap <Leader>' cs"'<CR>

" Expand word to tag
nmap <F4> byei<<ESC>ea></<C-R>0><ESC>bba

" Faster search
" nnoremap s /

" Fix indenting selection
vnoremap < <gv
vnoremap > >gv

" Open a new tab with Ctrl+T
nnoremap <C-t> <esc>:tabnew<CR>

" For indenting code
map <Leader>i mmgg=G`m<CR>

" Disable selection
nnoremap <Leader>n :nohl<CR>

" Enter replace command
nnoremap <Leader>r :%s/

" Edit vim config
nnoremap <Leader>ve :e $MYVIMRC<cr>

" Reload vim config
nnoremap <Leader>vr :source $MYVIMRC<cr>

" Reload servers
" nnoremap q :call RestartServers() <CR>
" nnoremap q :call

" Reload chrome tab
nnoremap R :call ReloadActiveChromeTab() <CR>

" Move up and down by visible lines if current line is wrapped
nmap j gj
nmap k gk
nmap K k

" nnoremap V 0v$

" Copy selected text to system clipboard
vnoremap m "+y

" Copy current line to system clipboard
nnoremap ` "+yy

" Easily resize windows
nnoremap < <C-w>10<
nnoremap > <C-w>10>
nnoremap + <C-w>5+
nnoremap _ <C-w>5-

" Move current line up
nnoremap <C-Up> :m .-2<CR>==
inoremap <C-Up> <ESC>:m .-2<CR>==gi

" Move multipe lines up in visual mode
vnoremap <C-Up> :m '<-2<CR>gv=gv

" Move current line down
nnoremap <C-Down> :m .+1<CR>==
inoremap <C-Down> <ESC>:m .+1<CR>==gi

" Move multipe lines down in visual mode
vnoremap <C-Down> :m '>+1<CR>gv=gv


" zoom a vim pane, <C-w>= to re-balance
" nmap <C-w><cr> <C-W>\| <C-W>_

" Switch between tabs
nnoremap <C-e> gt

" Tabs
nnoremap <C-Left> :tabprev<cr>
nnoremap <C-Right> :tabnext<cr>

" Map text align to tab button in visual mode
vnoremap <TAB> =

" Expand window
nmap " <C-W>\| <C-W>_

" Toggle windows layout mode
nnoremap K <C-w>H
nnoremap F <C-w>J

" Re-balance panes
nnoremap = <C-W>=

" Toggle current window zoom
nnoremap m :ToggleCurrentWindowZoom <CR>

" Swith between tabs
" nnoremap m gt

" Select tab by nuber
" 'ctrl-m 1' - selects first tab, etc
for i in range(1, 9)
  execute "nnoremap \<C-w>" . i . " " . i . "gt<CR>"
endfor

" TODO
for i in range(1, 5)
  execute "nnoremap \<Leader>" . i . " " . i . "gt<CR>"
endfor

" Yank, comment and paster (usefull for refactoring)
vnoremap M yV'] :TComment<CR>']pj
nnoremap M yy']:TComment<CR>']pj

" Faster close windows and quit
" nnoremap <C-c> <C-w>q
nnoremap <C-c> <C-w>q

" Test runner mappings
nnoremap <silent> <leader>t :TestNearest<CR>
nnoremap <silent> <leader>j :TestNearest<CR>
nnoremap <silent> <leader>T :TestFile<CR>
nnoremap <silent> <leader>a :TestSuite<CR>
nnoremap <silent> <leader>l :TestLast<CR>

" "Go to test file
" nmap t :A<CR> DEPRECATED

" Go to related file
nnoremap <Leader>e :R<CR>

" Go to alternate file
nnoremap q :A<CR>

" Tcomment
" Comment line in visual mode
vnoremap \ :TComment<CR>

" Comment line in normal mode
nnoremap \ :TComment<CR>

" fzf
set rtp+=~/.fzf

nnoremap <C-p> :FZ<cr>

" Ack mappings
nnoremap ! :Ack<SPACE>

" Ack: To go to the next search result
nnoremap <leader>] :cn<cr>

" Ack: To go to the previous search results
nnoremap <leader>[ :cp<cr>

" Full text search by FZF AG
noremap <Leader>p :Ag <cr>

" Search app/models by FZF
noremap <Leader>m :FZF app/models<CR>

" Search javascripts
noremap <Leader>u :FZF app/javascripts<CR>

" Search app/controllers by FZF
noremap <Leader>c :FZF app/controllers<CR>
nnoremap <silent> <Leader>f :Ag <C-R><C-W><CR>

" Unmap GitGutter leaders that I don't use. This avoids delays for other leaders.
" autocmd VimEnter * nunmap <leader>hp
" autocmd VimEnter * nunmap <leader>hr
" autocmd VimEnter * nunmap <leader>hs

"============================================================================
"====================== Plugins settings ====================================
"============================================================================

"Open ruby test in tmux pane
let test#strategy = "vimux"
"
" Use bundle exec for ruby tests
let test#ruby#bundle_exec = 1

" Run rspec with spring preloader
let test#ruby#rspec#executable = 'rsx'

" Use vertical tmux slpit for vimux commands
let g:VimuxOrientation = "h"

" Open vimux tmux pane with 50% width of screen
let g:VimuxHeight = "50"

" Ack (the_silver_searcher / ag)
let g:ackprg="ag"

let g:closetag_filenames = '*.html,*.xhtml,*.jsx, *.js'

" ===================== Fugitive settings ====================================
" Froce to split window verticaly when fugitive opens git diff
set diffopt+=vertical

" ===================== Nerdtree settings  ====================================
" Show hidden files
let NERDTreeShowHidden=1

let NERDTreeWinSize=40

" Disable default Ctrl-\ mapping
nnoremap <C-\> <NOP>

" Toggle NERDTree
nnoremap <C-\> :NERDTreeToggle<CR>
autocmd VimEnter * nnoremap <C-\> :NERDTreeToggle<CR>

" ===================== Emmet settings  ====================================
" Expand tag
" imap <C-l> <C-y>,
" imap <expr>k<tab> emmet#expandAbbrIntelligent("\<tab>")
" let g:user_emmet_settings = {
"   \  'javascript.jsx' : {
"     \      'extends' : 'jsx',
"     \  },
"   \}

" ===================== Syntastic settings  ====================================

" let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_error_symbol = '✗✗'
let g:syntastic_style_error_symbol = '✠✠'
let g:syntastic_warning_symbol = '∆∆'
let g:syntastic_style_warning_symbol = '≈≈'
let g:syntastic_ruby_checkers = ["mri", "rubocop -P -R"]

" ===================== ALE settings  ====================================
let g:ale_sign_error = '✗✗'
let g:ale_sign_warning = '∆∆'
let g:ale_lint_delay = 1000
let g:ale_lint_on_text_changed = 'never'

" ===================== vim-jsx ====================================
" default 0
let g:vim_jsx_pretty_colorful_config = 1

" vim-jsx
" By default, JSX syntax highlighting and indenting will be enabled only for
" files with the .jsx extension. If you would like JSX in .js files, add
let g:jsx_ext_required = 0


" ===================== Lightline settings  ====================================
let g:lightline = {
      \ 'colorscheme': 'one',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             ['filename', 'modified'] ],
      \   'right': [['zoom_status'], ['total_lines']],
      \ },
      \ 'inactive': {
      \   'left': [['filename'] ],
      \   'right': [['total_lines']],
      \ },
      \ 'component': {
      \   'total_lines': ' %l/%L '
      \ },
      \ 'component_function': {
      \   'zoom_status': 'IsCurrentWindowZoomed'
      \ },
      \}

function! IsCurrentWindowZoomed()
  if !exists("t:currentWindowZoomed")
    let t:currentWindowZoomed = 0
  end

  if t:currentWindowZoomed
    return '  ///          VIM WINDOW ZOOM            ///'
  else
    return ''
  endif
endfunction

" ===================== FZF settings  ====================================
" Customize fzf colors to match your color scheme
" let g:fzf_colors =
" \ { 'fg':      ['fg', 'Normal'],
"   \ 'bg':      ['bg', 'Normal'],
"   \ 'hl':      ['fg', 'Comment'],
"   \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
"   \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
"   \ 'hl+':     ['fg', 'Type'],
"   \ 'info':    ['fg', 'PreProc'],
"   \ 'border':  ['fg', 'Ignore'],
"   \ 'prompt':  ['fg', 'Conditional'],
"   \ 'pointer': ['fg', 'Exception'],
"   \ 'marker':  ['fg', 'Statement'],
"   \ 'spinner': ['fg', 'Label'],
"   \ 'header':  ['fg', 'Comment'] }


"============================================================================
"====================== Commands ===========================================
"============================================================================
command! ToggleCurrentWindowZoom :call ToggleCurrentWindowZoom()

" Fix save file typos
command! W w
command! WQ wq
command! Wq wq
command! Q q


"============================================================================
"====================== Functions ===========================================
"============================================================================

" DEPRECATED
" function! RestartServers()
"   execute system("tmux send-keys -t 2.left C-c \" bundle exec rails s\" C-m")
"   execute system("tmux send-keys -t 3.left C-c \" bundle exec rails s -p 3001\" C-m")
"   execute system("tmux send-keys -t 5.left C-c \" bundle exec sidekiq\" C-m")
"   echo "Servers reloaded"
" endfunction

function! ReloadActiveChromeTab()
  let l:currentTerminalEmulator = system("xdotool getactivewindow")

  execute system('
     \ xdotool search --onlyvisible --class Chrome windowfocus key F5
     \ && xdotool windowfocus ' . l:currentTerminalEmulator)

  echo "Chrome tab reloaded"
endfunction



" Toggle zoom of current window
function! ToggleCurrentWindowZoom()
  if !exists("t:currentWindowZoomed")
    let t:currentWindowZoomed = 0
    " TODO check nerdtree state
  endif

  if t:currentWindowZoomed
    execute "normal \<C-W>="
    let t:currentWindowZoomed = 0
  else
    :NERDTreeClose
    execute "normal \<C-W>\| \<C-W>_"
    let t:currentWindowZoomed = 1
  endif
endfunction


" ===================== FZF-AG functions  ====================================
" Full text search support for FZF
function! s:ag_to_qf(line)
  let parts = split(a:line, ':')
  return {'filename': parts[0], 'lnum': parts[1], 'col': parts[2],
        \ 'text': join(parts[3:], ':')}
endfunction

function! s:ag_handler(lines)
  if len(a:lines) < 2 | return | endif

  let cmd = get({'ctrl-x': 'split',
               \ 'ctrl-v': 'vertical split',
               \ 'ctrl-t': 'tabe'}, a:lines[0], 'e')
  let list = map(a:lines[1:], 's:ag_to_qf(v:val)')

  let first = list[0]
  execute cmd escape(first.filename, ' %#\')
  execute first.lnum
  execute 'normal!' first.col.'|zz'

  if len(list) > 1
    call setqflist(list)
    copen
    wincmd p
  endif
endfunction

" Ag command does full text search by FZF
command! -nargs=* Ag call fzf#run({
      \ 'source':  printf('ag --nogroup --column --color "%s"',
      \                   escape(empty(<q-args>) ? '^(?=.)' : <q-args>, '"\')),
      \ 'sink*':    function('<sid>ag_handler'),
      \ 'options': '--ansi --expect=ctrl-t,ctrl-v,ctrl-x --delimiter : --nth 4.. '.
      \            '--multi --bind=ctrl-a:select-all,ctrl-d:deselect-all '.
      \            '--color hl:68,hl+:110',
      \ 'down':    '50%'
      \ })

" Custom highlight function
" Requires vim 'set termguicolors'
function! Highlight(group, color)
  exec "hi " a:group . " guifg=" . a:color
endfunction

" Custom highlight function with italic text
" Requires vim 'set termguicolors'
function! ItalicHighlight(group, color)
  exec "hi " a:group . " guifg=" . a:color . " gui=italic"
endfunction

" ===================== Custom highlighting  ====================================
" hi! TabLine S
hi! link TabLineSel Function
" call Highlight('NERDTreeFile', 'gray')

" ===================== Experimental ====================================
" function! ToggleBackground()
" 	if ! exists('g:colors_name')
" 		echomsg 'No colorscheme set'
" 		return
" 	endif
" 	let l:scheme = g:colors_name
"
" 	if l:scheme =~# 'dark' || l:scheme =~# 'light'
" 		" Rotate between different theme backgrounds
" 		execute 'colorscheme' (l:scheme =~# 'dark'
" 					\ ? substitute(l:scheme, 'dark', 'light', '')
" 					\ : substitute(l:scheme, 'light', 'dark', ''))
" 	else
" 		execute 'set background='.(&background ==# 'dark' ? 'light' : 'dark')
" 		if ! exists('g:colors_name')
" 			execute 'colorscheme' l:scheme
" 			echomsg 'The colorscheme `'.l:scheme
" 				\ .'` doesn''t have background variants!'
" 		else
" 			echo 'Set colorscheme to '.&background.' mode'
" 		endif
" 	endif
" endfunction

" Save file
" nnoremap s :w<cr>

" Cursorline {{{
" Only show cursorline in the current window and in normal mode.
" augroup cline
"     au!
"     au WinLeave,InsertEnter * set nocursorline
"     au WinEnter,InsertLeave * set cursorline
" augroup END

" Save when losing focus
" au FocusLost * :silent! wall


" Modificate tabline
"turn off status line
" set tabline="what status line equals, or equaled or whatever"
" "set or change the color of the tabline
" hi tablinefill cterm=none ctermbg=blue ctermfg=white gui=none guibg=blue guifg=white
