-- require('gitsigns').setup({
--   signs = {
--     add          = { text = '+' },
--     change       = { text = '~' },
--     delete       = { text = '-' },
--     topdelete    = { text = '---' },
--     changedelete = { text = '~-' },
--     untracked    = { text = '~' },
--   },
--   signcolumn = true,  -- Toggle with `:Gitsigns toggle_signs`
-- })
