-- Ruby component toggle — lazy by virtue of its consumers.
--
-- All `s1`–`s4` keymaps in `keymappings/files.lua` invoke the module via
-- `<cmd>lua require("my_plugins.ruby_component_toggle").<fn>()<CR>` —
-- that require runs only on first keypress, not at startup. No
-- configurable surface and nothing to set up here, so this file is
-- header-only for symmetry with the rest of `plugin_settings/`.
