shared_buffer = 16GB
max_connections = 400
fsync = on
synchronous_commit = on
full_page_writes = off
wal_compression = off
wal_buffers = 16MB
min_wal_size = 2GB
max_wal_size = 4GB
checkpoint_completion_target = 0.9
work_mem = 33554KB
maintenance_work_mem = 2GB
wal_level=replica
