#!/usr/bin/env ruby

require 'rb-readline'
require 'readline'

# Search in pry history with fzf(https://github.com/junegunn/fzf)

def fzf_installed?
  !`which fzf`&.size&.zero?
end

if fzf_installed?
  def RbReadline.rl_reverse_search_history(_sign, _key)
    command = `cat #{Pry.config.history.file} | fzf --tac |  tr '\n' ' '`

    rl_insert_text(command)
  end
end
