require("plugin_settings/nvim_tree")
require("plugin_settings/nvim_devicons")
require("plugin_settings/neo_tree")
require("plugin_settings/lualine")
require("plugin_settings/fzf")
require("plugin_settings/telescope")
require('plugin_settings/treesitter')
require('plugin_settings/yaml_nvim')
require('plugin_settings/lsp_config')
require('plugin_settings/nvim_cmp')
-- require("plugin_settings/vim_rails")
require("plugin_settings/emmet")
require('plugin_settings/ack')
require('plugin_settings/ctags')
require('plugin_settings/vim_test')
require('plugin_settings/nvim_lint')
require('plugin_settings/conform_formater')
require('plugin_settings/luasnip')
require('plugin_settings/splitjoin')
require('plugin_settings/fugitive')
require('plugin_settings/nvim_autopairs')
require("plugin_settings/tabline_bufferline")
require('plugin_settings/nvim_scrollview')
require('plugin_settings/vim_illuminate')
require('plugin_settings/gitsigns')
require('plugin_settings/comment_nvim')
require('plugin_settings/gen_nvim')
-- require('plugin_settings/vim_markdown')
-- require("plugin_settings/git_conflict")
-- require('plugin_settings/colorizer')
-- require('plugin_settings/1_ror')

-- require('plugin_settings/indent_blankline')
-- require('plugin_settings/local_highlight')
-- require('plugin_settings/ale')
-- require('plugin_settings/nvim_snippy')

-- require("plugin_settings/lightbulb")

-- ====================== Vim highlight tag settings ======================
vim.cmd('highlight link matchTagError Todo')
vim.g.vim_matchtag_highlight_cursor_on = 1
