gesture swipe up 3 xdotool key 0xff50
gesture swipe down 3 xdotool key 0xff57
gesture swipe left 3 xdotool key ctrl+0xff55
gesture swipe right 3 xdotool key ctrl+0xff56

gesture pinch in 3 i3-msg kill

gesture swipe up 4 xdotool key super+0xff0d
gesture swipe down 4 xdotool key super+b
gesture swipe left 4 xdotool key super+shift+s
