# font_family MesloLGM Nerd Font Bold
# font_family Monego-Bold
# font_family Monego
# font_family  Meslo LG M Bold Nerd Font Complete Mono
# font_family  MesloLGS Nerd Font Bold
font_family CaskaydiaMono Nerd Font Bold
# font_family JetBrainsMono Semi Bold

bold_font        bold
italic_font      auto
bold_italic_font auto

font_size 14
#adjust_line_height 1

#text_composition_strategy 0.01 1
text_composition_strategy legacy

confirm_os_window_close 0

# Base16 Horizon Dark - kitty color config
# https://github.com/kdrag0n/base16-kitty
# Scheme by Michaël Ball (http://github.com/michael-ball/)
# background #1c1e26
# foreground #ecf0f2
# selection_background #cbced0
# selection_foreground #1c1e26
# url_color #9da0a2
# cursor #cbced0
# active_border_color #6f6f70
# inactive_border_color #232530
# active_tab_background #1c1e26
# active_tab_foreground #cbced0
# inactive_tab_background #232530
# inactive_tab_foreground #9da0a2
# tab_bar_background #232530

# # normal
# color0 #1c1e26
# color1 #e95678
# color2 #29d398
# color3 #fac29a
# color4 #26bbd9
# color5 #ee64ac
# color6 #59e1e3
# color7 #cbced0

# # bright
# color8 #6f6f70
# color9 #fab795
# color10 #232530
# color11 #2e303e
# color12 #9da0a2
# color13 #dcdfe4
# color14 #f09383
# color15 #e3e6ee


# Catppuccin macchiato
# https://github.com/catppuccin/kitty
# The basic colors
# foreground              #cad3f5
foreground              #ced7fa

# Catppuccin custom background color
# background              #252633
background              #212433
# Default macchiato background color
# background              #24273a

selection_foreground    #24273a
selection_background    #f4dbd6

# Cursor colors
cursor                  #f4dbd6
cursor_text_color       #24273a

# URL underline color when hovering with mouse
url_color               #f4dbd6

# Kitty window border colors
active_border_color     #b7bdf8
inactive_border_color   #6e738d
bell_border_color       #eed49f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #181926
active_tab_background   #c6a0f6
inactive_tab_foreground #cad3f5
inactive_tab_background #1e2030
tab_bar_background      #181926

# Colors for marks (marked text in the terminal)
mark1_foreground #24273a
mark1_background #b7bdf8
mark2_foreground #24273a
mark2_background #c6a0f6
mark3_foreground #24273a
mark3_background #7dc4e4

# The 16 terminal colors

# black
color0 #494d64
color8 #5b6078

# red
color1 #ed8796
color9 #ed8796

# green
color2  #a6da95
color10 #a6da95

# yellow
color3  #eed49f
color11 #eed49f

# blue
color4  #8aadf4
color12 #8aadf4

# magenta
color5  #f5bde6
color13 #f5bde6

# cyan
color6  #8bd5ca
color14 #8bd5ca

# white
color7  #b8c0e0
color15 #a5adcb
