# monitor.alsa.rules = [
#   {
#     matches = [
#       {
#         device.nick = "HDA Intel PCH"
#       }
#     ]
#     actions = {
#       update-props = {
#         api.alsa.use-acp = true,
#         api.acp.auto-profile = false
#         api.acp.auto-port = false
#         device.profile-set = "multiple.conf"
#         device.profile = "multiple"
#       }
#     }
#   }
# ]
